### ISSUE TITLE
Usage w/ nuxt-typescript

### ISSUE THREAD

**Issue by flrnt** [fringers/vue-deprecate#22]
@JKrol @fabianem 
nice work guyz.
Bit lack of documentation about usage in a nuxt ts project.
How do you treat `deprecated: true` with 'nuxt-property-decorator'

**Comment by JKrol** [comment]
Hello @flrnt !
Thank you for the kind words. We have just released a new version ([v0.3.2](https://github.com/fringers/vue-deprecate/releases/tag/v0.3.2)) with better support for Nuxt.js and `nuxt-property-decorator`.

If you want to try it, you should:
1. Install the latest version of `vue-deprecate` (0.3.2 or newer)
2. Create file `plugins/vue-deprecate.js`:
```js
import Vue from 'vue'
import VueDeprecate from 'vue-deprecate';

Vue.use(VueDeprecate);
```
3. Add the file path inside the `plugins` key of `nuxt.config.js`:
```js
export default {
  plugins: ['@/plugins/vue-deprecate.js']
}
```
4. Use `vue-depreacte` in your components:
```js
import { Vue, Component } from 'nuxt-property-decorator'

@Component({
  deprecated: true,
})
export default class Test extends Vue {
}
```

Please let us know if you need more support and if it worked correctly.
